function Countingresults1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COUNTINGRESULTS1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  COUNTINGRESULTS1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Countingresults1 = importfile("/Users/zhangguangxin/Desktop/汤超/模拟/Counting_results.tsv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Dec-2022 19:13:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ZSJ_ZGX_Repeat_Cell_concentrationml1", "ZSJ_ZGX_Repeat_1", "ZSJ_ZGX_Repeat_2", "ZSJ_ZGX_Control_Cell_concentrationml1", "ZSJ_ZGX_Control", "ZTY_Cell_concentrationml1", "ZTY_Experimental", "ZTY_Cell_concentrationml2", "ZTY_Control", "WL_Cell_concentrationml1", "WL_Experimental", "WL_Cell_concentrationml2", "WL_Control", "TYX_Cell_concentrationml1", "TYX_Experimental", "TYX_Cell_concentrationml2", "TYX_Control"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Countingresults1 = readtable(filename, opts);

end